// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/dart_types.dart';
import '../core/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<int> initPjsua({
  required int localPort,
  required TransportMode transportMode,
  required OnIncommingCall incomingCallStrategy,
  required String stunSrv,
  required String uri,
}) => RustLib.instance.api.crateApiSimpleInitPjsua(
  localPort: localPort,
  transportMode: transportMode,
  incomingCallStrategy: incomingCallStrategy,
  stunSrv: stunSrv,
  uri: uri,
);

Stream<CallInfo> registerCallStream() =>
    RustLib.instance.api.crateApiSimpleRegisterCallStream();

Future<void> markCallAlive({required int callId}) =>
    RustLib.instance.api.crateApiSimpleMarkCallAlive(callId: callId);

Future<int> makeCall({required String phoneNumber, required String domain}) =>
    RustLib.instance.api.crateApiSimpleMakeCall(
      phoneNumber: phoneNumber,
      domain: domain,
    );

Future<void> hangupCall({required int callId}) =>
    RustLib.instance.api.crateApiSimpleHangupCall(callId: callId);

Future<int> destroyPjsua() => RustLib.instance.api.crateApiSimpleDestroyPjsua();
