name: flutter_rust_sip
description: "A cross-platform SIP client built over PJSIP project for Flutter using C/Rust FFI."
repository: https://github.com/omortie/flutter_rust_sip
home: https://github.com/omortie/flutter_rust_sip
version: 1.0.1

topics: 
  - sip
  - network
  - ffi
  - webrtc

platforms:
  linux:
  windows:
  android:  


environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.11.1
  freezed_annotation: ^3.1.0
  hooks: ^1.0.3
  native_toolchain_rust: ^1.0.3
  rxdart: ^0.28.0

dev_dependencies:
  ffi: ^2.2.0
  ffigen: ^13.0.0
  freezed: ^3.2.5
  build_runner: ^2.14.1
  flutter_lints: ^5.0.0
  
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
