// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'dart_types.freezed.dart';

@freezed
sealed class CallState with _$CallState {
  const CallState._();

  const factory CallState.early() = CallState_Early;
  const factory CallState.calling() = CallState_Calling;
  const factory CallState.connecting() = CallState_Connecting;
  const factory CallState.confirmed() = CallState_Confirmed;
  const factory CallState.disconnected() = CallState_Disconnected;
  const factory CallState.error(String field0) = CallState_Error;
}

@freezed
sealed class SessionState with _$SessionState {
  const SessionState._();

  const factory SessionState.initialized() = SessionState_Initialized;
  const factory SessionState.running() = SessionState_Running;
  const factory SessionState.stopped() = SessionState_Stopped;
  const factory SessionState.error(String field0) = SessionState_Error;
}
