// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

enum OnIncommingCall { autoAnswer, ignore }

@freezed
sealed class TelephonyError with _$TelephonyError implements FrbException {
  const TelephonyError._();

  const factory TelephonyError.creationError(String field0) =
      TelephonyError_CreationError;
  const factory TelephonyError.configError(String field0) =
      TelephonyError_ConfigError;
  const factory TelephonyError.initializationError(String field0) =
      TelephonyError_InitializationError;
  const factory TelephonyError.transportError(String field0) =
      TelephonyError_TransportError;
  const factory TelephonyError.dtmfError(String field0) =
      TelephonyError_DTMFError;
  const factory TelephonyError.callCreationError(String field0) =
      TelephonyError_CallCreationError;
  const factory TelephonyError.callStatusUpdateError(String field0) =
      TelephonyError_CallStatusUpdateError;
  const factory TelephonyError.accountCreationError(String field0) =
      TelephonyError_AccountCreationError;
  const factory TelephonyError.telephonyStartError(String field0) =
      TelephonyError_TelephonyStartError;
  const factory TelephonyError.telephonyDestroyError(String field0) =
      TelephonyError_TelephonyDestroyError;
  const factory TelephonyError.inputValueError(String field0) =
      TelephonyError_InputValueError;
}

enum TransportMode { tcp, udp, tls, udp6, tcp6, tls6 }
