// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

int ffiAccountSetup({
  required String username,
  required String password,
  required String uri,
  required bool p2P,
}) => RustLib.instance.api.crateApiLibFfiAccountSetup(
  username: username,
  password: password,
  uri: uri,
  p2P: p2P,
);

Future<int> ffiMakeCall({
  required String phoneNumber,
  required String domain,
}) => RustLib.instance.api.crateApiLibFfiMakeCall(
  phoneNumber: phoneNumber,
  domain: domain,
);

Future<int> ffiSendDtmf({required int digit}) =>
    RustLib.instance.api.crateApiLibFfiSendDtmf(digit: digit);

Future<void> ffiHangupCalls() =>
    RustLib.instance.api.crateApiLibFfiHangupCalls();
