// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/dart_types.dart';
import '../core/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SESSION_COUNTER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

PlatformInt64 createNewSession() =>
    RustLib.instance.api.crateApiSimpleCreateNewSession();

Stream<CallState> initTelephony({
  required PlatformInt64 sessionId,
  required int localPort,
  required TransportMode transportMode,
  required OnIncommingCall incomingCallStrategy,
}) => RustLib.instance.api.crateApiSimpleInitTelephony(
  sessionId: sessionId,
  localPort: localPort,
  transportMode: transportMode,
  incomingCallStrategy: incomingCallStrategy,
);

int ffiAccountSetup({
  required String username,
  required String password,
  required String uri,
  required bool p2P,
}) => RustLib.instance.api.crateApiSimpleFfiAccountSetup(
  username: username,
  password: password,
  uri: uri,
  p2P: p2P,
);

Future<int> ffiMakeCall({
  required String phoneNumber,
  required String domain,
}) => RustLib.instance.api.crateApiSimpleFfiMakeCall(
  phoneNumber: phoneNumber,
  domain: domain,
);

Future<void> ffiHangupCalls() =>
    RustLib.instance.api.crateApiSimpleFfiHangupCalls();
